apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-egressgateway
  namespace: istio-egressgateway
spec:
  dependsOn:
    - name: istiod
      namespace: istio-system
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    service:
      type: ClusterIP
  interval: 1h0m0s
  releaseName: istio-egressgateway
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
