apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./istio/system
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-ingress
  namespace: flux-system
spec:
  depends_on:
    - name: istio-system
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./istio/ingress
  prune: true
  validation: client
